// Generated by Skyramp v1.3.34 on 2026-07-15 14:13:31.695687778 +0000 UTC m=+377.347401393
// Command: skyramp generate contract rest http://localhost:3000/api/trpc/eventTypes/upsertRecurring \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_upsert_recurring_count_boundary.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/.skyramp/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"json":{"eventTypeId":1,"frequency":"WEEKLY","count":366,"interval":1}} \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/trpc/eventTypes/upsertRecurring POST
test('testUpsertRecurringPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const upsertRecurringPostRequestBody: string = `{
        "json": {
            "count": 366,
            "eventTypeId": 1,
            "frequency": "WEEKLY",
            "interval": 1
        }
    }`;

    // Execute Request
    const upsertRecurringPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/trpc/eventTypes/upsertRecurring",
        method: "POST",
        body: upsertRecurringPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(upsertRecurringPostResponse.statusCode, 'status code').toBe(400);
    // ZGetRecurringInputSchema caps count at z.number().int().min(0).max(365); the shared
    // errorFormatter (packages/trpc/server/errorFormatter.ts) returns this exact shape for a
    // ZodError cause.
    expect(getValue(upsertRecurringPostResponse, "error.json.message"), 'error.json.message').toBe("Invalid input");
    expect(getValue(upsertRecurringPostResponse, "error.json.code"), 'error.json.code').toBe(400);
    expect(getValue(upsertRecurringPostResponse, "error.json.data.code"), 'error.json.data.code').toBe("BAD_REQUEST");
    expect(getValue(upsertRecurringPostResponse, "error.json.data.httpStatus"), 'error.json.data.httpStatus').toBe(400);
    expect(getValue(upsertRecurringPostResponse, "error.json.data.path"), 'error.json.data.path').toBe("eventTypes.upsertRecurring");
    expect(getValue(upsertRecurringPostResponse, "error.json.data.zodError.fieldErrors.count.0"), 'zodError.fieldErrors.count.0').not.toBeNull();
});
