// Generated by Skyramp v1.3.34 on 2026-07-15 14:13:28.629212658 +0000 UTC m=+374.280926303
// Command: skyramp generate contract rest http://localhost:3000/api/trpc/eventTypes/getRecurring \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_recurring_not_found.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/.skyramp/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params input={"json":{"eventTypeId":999999}} \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/trpc/eventTypes/getRecurring GET
test('testGetRecurringGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const getRecurringGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/trpc/eventTypes/getRecurring",
        method: "GET",
        headers: headers,
        queryParams: {"input": "{\"json\":{\"eventTypeId\":999999}}"}
    });

    // Generated Assertions
    expect(getRecurringGetResponse.statusCode, 'status code').toBe(404);
    // getRecurringHandler throws a bare `new Error(...)` for a not-found/inaccessible event type
    // instead of `new TRPCError({ code: "NOT_FOUND" })`, so tRPC's error middleware currently
    // returns INTERNAL_SERVER_ERROR (500) with a different error envelope. These assertions
    // document the correct tRPC NOT_FOUND contract and are expected to FAIL against the current
    // implementation.
    expect(getValue(getRecurringGetResponse, "error.json.data.code"), 'error.json.data.code').toBe("NOT_FOUND");
    expect(getValue(getRecurringGetResponse, "error.json.data.httpStatus"), 'error.json.data.httpStatus').toBe(404);
    expect(getValue(getRecurringGetResponse, "error.json.data.path"), 'error.json.data.path').toBe("eventTypes.getRecurring");
});
