// Generated by Skyramp v1.3.34 on 2026-07-15 14:13:37.953829255 +0000 UTC m=+383.605542880
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output recurring_config_upsert_drops_enddate_on_partial_update_integration_test.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/.skyramp/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/calcom/calcom/.skyramp/tests/scenario_recurring_config_upsert_drops_enddate_on_partial_update.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const upsertRecurringPostRequestBody: string = `{
        "json": {
            "count": 10,
            "endDate": "2026-12-31T00:00:00.000Z",
            "eventTypeId": 1,
            "frequency": "WEEKLY",
            "interval": 1
        }
    }`;

    // Execute Request
    const upsertRecurringPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/eventTypes/upsertRecurring",
        method: "POST",
        body: upsertRecurringPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(upsertRecurringPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(upsertRecurringPostResponse, "result.data.json.eventTypeId"), 'eventTypeId').toBe(1);
    expect(getValue(upsertRecurringPostResponse, "result.data.json.updated"), 'updated').toBe(true);

    // Request Body
    const upsertRecurringPost1RequestBody: string = `{
        "json": {
            "count": 10,
            "eventTypeId": 1,
            "frequency": "MONTHLY",
            "interval": 1
        }
    }`;

    // Execute Request
    const upsertRecurringPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/eventTypes/upsertRecurring",
        method: "POST",
        body: upsertRecurringPost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(upsertRecurringPost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(upsertRecurringPost1Response, "result.data.json.eventTypeId"), 'eventTypeId').toBe(1);
    expect(getValue(upsertRecurringPost1Response, "result.data.json.updated"), 'updated').toBe(true);

    // Execute Request
    const getRecurringGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/eventTypes/getRecurring",
        method: "GET",
        headers: headers,
        queryParams: {"input": ["{\"json\":{\"eventTypeId\":1}}"]}
    });

    // Generated Assertions
    expect(getRecurringGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(getRecurringGetResponse, "result.data.json.eventTypeId"), 'eventTypeId').toBe(1);
    expect(getValue(getRecurringGetResponse, "result.data.json.frequency"), 'frequency').toBe("MONTHLY");
    expect(getValue(getRecurringGetResponse, "result.data.json.count"), 'count').toBe(10);
    expect(getValue(getRecurringGetResponse, "result.data.json.interval"), 'interval').toBe(1);
    // This assertion documents the merge bug: upsertRecurring's docstring claims it merges the
    // incoming config with existing RRULE fields, but the handler discards the previously-fetched
    // recurringEvent and overwrites the whole JSON blob. The second upsertRecurring call above
    // only changed frequency/count/interval and omitted endDate, so a correct merge would still
    // return the endDate set by the first call. This assertion is expected to FAIL on the current
    // implementation because endDate is silently dropped.
    expect(getValue(getRecurringGetResponse, "result.data.json.endDate"), 'endDate').toBe("2026-12-31T00:00:00.000Z");
});
