// Generated by Skyramp v1.3.34 on 2026-07-15 14:55:13.655191045 +0000 UTC m=+605.796891312
// Command: skyramp generate contract rest http://localhost:3000/api/trpc/availability/schedule.get \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output availability_default_schedule_end_time_contract.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/.skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-data {"result":{"data":{"json":{"schedule":[{"days":[1,2,3,4,5],"startTime":"1970-01-01T09:00:00.000Z","endTime":"1970-01-01T18:00:00.000Z"}]}}}} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/trpc/availability/schedule.get GET
test('testScheduleGetGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedScheduleGetGetResponseBody: string = `{
        "result": {
            "data": {
                "json": {
                    "schedule": [
                        {
                            "days": [
                                1,
                                2,
                                3,
                                4,
                                5
                            ],
                            "endTime": "1970-01-01T18:00:00.000Z",
                            "startTime": "1970-01-01T09:00:00.000Z"
                        }
                    ]
                }
            }
        }
    }`;

    // Execute Request
    const scheduleGetGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/trpc/availability/schedule.get",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(scheduleGetGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(scheduleGetGetResponse, expectedScheduleGetGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.days.0"), 'days.0').toBe(1);
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.days.1"), 'days.1').toBe(2);
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.days.2"), 'days.2').toBe(3);
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.days.3"), 'days.3').toBe(4);
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.days.4"), 'days.4').toBe(5);
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.days.5"), 'days.5').toBeUndefined();
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.startTime"), 'startTime').toBe("1970-01-01T09:00:00.000Z");
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.0.endTime"), 'endTime').toBe("1970-01-01T18:00:00.000Z");
    expect(getResponseValue(scheduleGetGetResponse, "result.data.json.schedule.1"), 'schedule.1').toBeUndefined();
});
