// Generated by Skyramp v1.3.34 on 2026-07-15 14:16:44.935621615 +0000 UTC m=+603.723318595
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output booking_flow_check_then_create_happy_path_integration_test.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/packages/trpc/server/routers/viewer/bookings/skyramp-tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/calcom/calcom/packages/trpc/server/routers/viewer/bookings/skyramp-tests/scenario_booking_flow_check_then_create_happy_path.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const checkBookingAvailabilityGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/checkBookingAvailability",
        method: "GET",
        headers: headers,
        queryParams: {"input": ["{\"json\":{\"eventTypeId\":1,\"startTime\":\"2026-07-19T14:00:00.000Z\",\"endTime\":\"2026-07-19T14:30:00.000Z\",\"timeZone\":\"UTC\"}}"]}
    });

    // Generated Assertions
    expect(checkBookingAvailabilityGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.available"), 'available').toBe(true);
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.reason"), 'reason').toBeNull();
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.nextAvailableSlot"), 'nextAvailableSlot').toBeNull();

    // Request Body
    const createBookingFlowPostRequestBody: string = `{
        "json": {
            "email": "carol.creator+ts2@example.com",
            "endTime": "2026-07-19T14:30:00.000Z",
            "eventTypeId": 1,
            "language": "en",
            "name": "Carol Creator",
            "notes": "Discuss Q3 roadmap",
            "startTime": "2026-07-19T14:00:00.000Z",
            "timeZone": "UTC"
        }
    }`;

    // Execute Request
    const createBookingFlowPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/createBookingFlow",
        method: "POST",
        body: createBookingFlowPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(createBookingFlowPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(createBookingFlowPostResponse, "result.data.json.uid"), 'uid').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(createBookingFlowPostResponse, "result.data.json.title"), 'title').toBe("Carol Creator <> Testbot 30 Min");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.startTime"), 'startTime').toBe("2026-07-19T14:00:00.000Z");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.endTime"), 'endTime').toBe("2026-07-19T14:30:00.000Z");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.attendeeName"), 'attendeeName').toBe("Carol Creator");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.attendeeEmail"), 'attendeeEmail').toBe("carol.creator+ts2@example.com");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.status"), 'status').toBe("ACCEPTED");
});
