// Generated by Skyramp v1.3.34 on 2026-07-15 14:16:47.26831078 +0000 UTC m=+606.056007750
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output booking_flow_minimum_notice_enforcement_integration_test.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/packages/trpc/server/routers/viewer/bookings/skyramp-tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/calcom/calcom/packages/trpc/server/routers/viewer/bookings/skyramp-tests/scenario_booking_flow_minimum_notice_enforcement.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const input = "{\"json\":{\"eventTypeId\":1,\"startTime\":\"2026-07-20T09:00:00.000Z\",\"endTime\":\"2026-07-20T09:30:00.000Z\",\"timeZone\":\"UTC\"}}";

    // Execute Request
    const checkBookingAvailabilityGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/checkBookingAvailability",
        method: "GET",
        headers: headers,
        queryParams: {"input": ["{\"json\":{\"eventTypeId\":1,\"startTime\":\"2026-07-15T14:22:00.000Z\",\"endTime\":\"2026-07-15T14:52:00.000Z\",\"timeZone\":\"UTC\"}}"]}
    });

    // Generated Assertions
    expect(checkBookingAvailabilityGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.available"), 'available').toBe(false);
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.reason"), 'reason').toBe("Booking requires at least 120 minutes notice");
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.nextAvailableSlot"), 'nextAvailableSlot').toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);

    // Execute Request
    const checkBookingAvailabilityGet1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/checkBookingAvailability",
        method: "GET",
        headers: headers,
        queryParams: {"input": ["{\"json\":{\"eventTypeId\":1,\"startTime\":\"2026-07-20T09:00:00.000Z\",\"endTime\":\"2026-07-20T09:30:00.000Z\",\"timeZone\":\"UTC\"}}"]}
    });

    // Generated Assertions
    expect(checkBookingAvailabilityGet1Response.statusCode, 'status code').toBe(200);
    expect(getValue(checkBookingAvailabilityGet1Response, "result.data.json.available"), 'available').toBe(true);
    expect(getValue(checkBookingAvailabilityGet1Response, "result.data.json.reason"), 'reason').toBeNull();
    expect(getValue(checkBookingAvailabilityGet1Response, "result.data.json.nextAvailableSlot"), 'nextAvailableSlot').toBeNull();
});
