// Generated by Skyramp v1.3.34 on 2026-07-15 14:16:42.421640502 +0000 UTC m=+601.209337492
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output booking_flow_conflict_double_booking_integration_test.spec.ts \
// 		--output-dir /home/runner/work/calcom/calcom/packages/trpc/server/routers/viewer/bookings/skyramp-tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/calcom/calcom/packages/trpc/server/routers/viewer/bookings/skyramp-tests/scenario_booking_flow_conflict_double_booking.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const createBookingFlowPostRequestBody: string = `{
        "json": {
            "email": "alice.booker+ts1@example.com",
            "endTime": "2026-07-18T10:30:00.000Z",
            "eventTypeId": 1,
            "language": "en",
            "name": "Alice Booker",
            "startTime": "2026-07-18T10:00:00.000Z",
            "timeZone": "UTC"
        }
    }`;

    // Execute Request
    const createBookingFlowPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/createBookingFlow",
        method: "POST",
        body: createBookingFlowPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(createBookingFlowPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(createBookingFlowPostResponse, "result.data.json.uid"), 'uid').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(createBookingFlowPostResponse, "result.data.json.title"), 'title').toBe("Alice Booker <> Testbot 30 Min");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.startTime"), 'startTime').toBe("2026-07-18T10:00:00.000Z");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.endTime"), 'endTime').toBe("2026-07-18T10:30:00.000Z");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.attendeeName"), 'attendeeName').toBe("Alice Booker");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.attendeeEmail"), 'attendeeEmail').toBe("alice.booker+ts1@example.com");
    expect(getValue(createBookingFlowPostResponse, "result.data.json.status"), 'status').toBe("ACCEPTED");

    // Execute Request
    const checkBookingAvailabilityGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/checkBookingAvailability",
        method: "GET",
        headers: headers,
        queryParams: {"input": ["{\"json\":{\"eventTypeId\":1,\"startTime\":\"2026-07-18T10:15:00.000Z\",\"endTime\":\"2026-07-18T10:45:00.000Z\",\"timeZone\":\"UTC\"}}"]}
    });

    // Generated Assertions
    expect(checkBookingAvailabilityGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.available"), 'available').toBe(false);
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.reason"), 'reason').toBe("Slot is already booked");
    expect(getValue(checkBookingAvailabilityGetResponse, "result.data.json.nextAvailableSlot"), 'nextAvailableSlot').toBe(getValue(createBookingFlowPostResponse, "result.data.json.endTime"));

    // Request Body
    const createBookingFlowPost1RequestBody: string = `{
        "json": {
            "email": "bob.overbook+ts1@example.com",
            "endTime": "2026-07-18T10:45:00.000Z",
            "eventTypeId": 1,
            "language": "en",
            "name": "Bob Overbook",
            "startTime": "2026-07-18T10:15:00.000Z",
            "timeZone": "UTC"
        }
    }`;

    // Execute Request
    const createBookingFlowPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/bookings/createBookingFlow",
        method: "POST",
        body: createBookingFlowPost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(createBookingFlowPost1Response.statusCode, 'status code').toBe(409);
});
